package rv.experience.client;

import com.norwood.mcheli.vm.VMController;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.client.gui.GuiScreen;
import org.lwjgl.input.Keyboard;
import rv.experience.protocol.ExperienceProtocol.Action;

public final class ExperienceScreen extends GuiScreen {
    public int tab,controlsPage,gearSlot,gearPage,buttonPage,feelPage;
    private int left,top,width,height,focus=-1;
    private long paintedRevision=-1;
    private boolean paintedPending;
    private ControlDraft controls;
    private final List<Button> buttons=new ArrayList<Button>();
    private static final String[] FEEL={"deadzone","expo","rate","smoothing","throttleSmoothing","throttleExpo","angleLimit","cameraRoll","throttleRate"};
    private static final double[] DEFAULT={.04,.35,110,.07,.07,0,35,.55,.44},STEP={.01,.05,5,.005,.005,.05,1,.05,.05},MIN={0,0,45,.005,.005,0,15,0,.1},MAX={.3,.8,240,.2,.2,.7,60,1,1.2};
    private static final class Button {int id,x,y,w,h;String label;boolean enabled;Object nativeButton;Button(int id,int x,int y,int w,int h,String label,boolean enabled){this.id=id;this.x=x;this.y=y;this.w=w;this.h=h;this.label=label;this.enabled=enabled;nativeButton=Native.create("net.minecraft.client.gui.GuiButton",new Class<?>[]{int.class,int.class,int.class,int.class,int.class,String.class},id,x,y,w,h,label);Native.set(nativeButton,"field_146124_l",enabled);}}
    public ExperienceScreen(int tab){this.tab=tab;}
    public boolean english(){return ClientProxy.state!=null&&ClientProxy.state.english;}
    private String tr(String ru,String en){return english()?en:ru;}
    public void func_73866_w_(){width=Math.min(660,field_146294_l-16);height=Math.min(390,field_146295_m-16);left=(field_146294_l-width)/2;top=(field_146295_m-height)/2;rebuild();}
    public boolean func_73868_f(){return false;}
    public void func_73876_c(){if(controls!=null&&tab==2)controls.poll();ClientState s=ClientProxy.state;if((s==null?-1:s.revision)!=paintedRevision||ClientProxy.pending!=paintedPending)rebuild();}
    public void func_146281_b(){VMController.INSTANCE.poll(false);}
    private void button(int id,int x,int y,int w,String label,boolean enabled){buttons.add(new Button(id,x,y,w,18,label,enabled));}
    private void line(String text,int x,int y,int color,int w){Native.text(text,x,y,color,w);}
    private int body(){return top+62;}
    private int rows(){return Math.max(3,(height-132)/22);}
    private boolean available(){return ClientProxy.state!=null&&!ClientProxy.pending;}
    private void rebuild(){buttons.clear();ClientState s=ClientProxy.state;paintedRevision=s==null?-1:s.revision;paintedPending=ClientProxy.pending;int third=(width-24)/3;String[] tabs={tr("Сессия","Session"),tr("Снаряжение","Gear"),tr("Управление","Controls")};for(int i=0;i<3;i++)button(10+i,left+8+i*(third+4),top+32,third,(tab==i?"• ":"")+tabs[i],true);button(1,left+width-26,top+8,18,"×",true);button(2,left+width-91,top+8,60,english()?"RU":"EN",available());if(tab==0)sessionButtons();else if(tab==1)gearButtons();else controlButtons();focus=Math.min(focus,buttons.size()-1);}
    private void sessionButtons(){ClientState s=ClientProxy.state;int y=body()+30,col=(width-24)/3;String[] modes={tr("Свободная игра","Freeplay"),tr("Тренировка","Training"),tr("Командный бой","Team round")};for(int i=0;i<3;i++)button(100+i,left+8+i*(col+4),y,col,(s!=null&&s.mode==i?"• ":"")+modes[i],available()&&(s==null||s.phase!=2));y+=28;String[] teams={tr("Синие","Blue"),tr("Красные","Red"),tr("Автовыбор","Auto")};for(int i=0;i<3;i++)button(110+i,left+8+i*(col+4),y,col,teams[i],available()&&s.mode==2&&s.phase!=2);y+=28;button(120,left+8,y,col,s!=null&&s.ready?tr("Не готов","Not ready"):tr("Готов","Ready"),available()&&s.mode==2&&s.team!=0&&s.gearConfirmed&&s.phase!=2);button(121,left+12+col,y,col,tr("Голос за старт","Vote to start"),available()&&s.mode==2&&s.ready&&s.phase==0);button(122,left+16+col*2,y,col,tr("Отменить готовность","Cancel readiness"),available()&&s.ready&&s.phase!=2);int bottom=top+height-53;button(130,left+8,bottom,col,tr("В лобби","Go to lobby"),available()&&s.phase!=2);button(131,left+12+col,bottom,col,tr("На полигон","Go to training"),available()&&s.phase!=2);button(132,left+16+col*2,bottom,col,tr("Руководство","Guide"),available());}
    private void gearButtons(){ClientState s=ClientProxy.state;int y=body(),w=(width-24)/7;String[] slots={tr("Осн.","Gun"),tr("Пст.","Side"),tr("Броня","Armor"),tr("Дрон","UAV"),tr("Мед.","Med"),tr("Еда","Food"),tr("БК","Ammo")};for(int i=0;i<7;i++)button(200+i,left+8+i*(w+2),y,w,(gearSlot==i?"•":"")+slots[i],true);y+=26;List<ClientState.Choice> choices=slotChoices();int count=Math.max(1,(height-195)/22);button(220,left+8,y,width-100,tr("Без предмета","None"),available()&&s.canEditGear);button(221,left+width-86,y,36,"<",gearPage>0);button(222,left+width-46,y,36,">",(gearPage+1)*count<choices.size());for(int i=0;i<count&&gearPage*count+i<choices.size();i++){ClientState.Choice c=choices.get(gearPage*count+i);button(1000+c.id,left+8,y+22*(i+1),width-16,(s!=null&&s.selection[gearSlot]==c.id?"• ":"")+c.label(english())+" · "+c.cost,available()&&s.canEditGear);}int bottom=top+height-53;button(230,left+8,bottom,(width-24)/2,tr("Получить выбранное","Equip selection"),available()&&s.canEditGear&&s.cost<=s.budget&&s.requiredSlots<=s.freeSlots&&s.requiredSlots>0&&s.cooldownSeconds==0);button(231,left+12+(width-24)/2,bottom,(width-24)/2,tr("Оставить своё","Keep my gear"),available()&&s.canEditGear);if(s!=null&&!s.presets.isEmpty()){int presetWidth=(width-24)/s.presets.size();for(int i=0;i<s.presets.size();i++){ClientState.Preset p=s.presets.get(i);button(300+i,left+8+i*(presetWidth+1),top+height-88,presetWidth,p.label(english()),available()&&s.canEditGear);}}}
    private List<ClientState.Choice> slotChoices(){List<ClientState.Choice> list=new ArrayList<ClientState.Choice>();if(ClientProxy.state!=null)for(ClientState.Choice c:ClientProxy.state.catalog)if(c.slot==gearSlot)list.add(c);return list;}
    private void controlButtons(){if(controls==null)controls=new ControlDraft();int q=(width-28)/4,y=body();String[] names={tr("Устройство","Device"),tr("Оси","Axes"),tr("Плавность","Feel"),tr("Кнопки","Buttons")};for(int i=0;i<4;i++)button(400+i,left+8+i*(q+4),y,q,(controlsPage==i?"• ":"")+names[i],true);y+=26;int half=(width-24)/2;if(controlsPage==0){button(410,left+8,y,half,tr("Обновить USB","Scan USB"),true);button(411,left+12+half,y,half,controls.device==null?tr("Выбрать устройство","Select device"):controls.device.getName(),true);y+=height<270?19:23;button(412,left+8,y,half,tr("Ввод: ","Input: ")+(controls.flag("enabled","false")?tr("контроллер","controller"):tr("клавиатура","keyboard")),true);button(413,left+12+half,y,half,controls.profile.getProperty("kind","radio").equals("radio")?tr("Пульт / RadioMaster","Radio / RadioMaster"):tr("Геймпад / PS / Xbox","Gamepad / PS / Xbox"),true);y+=height<270?19:23;button(414,left+8,y,half,controls.profile.getProperty("flight","angle").equals("angle")?tr("Angle: стабилизация","Angle: stabilized"):"Acro",true);button(415,left+12+half,y,half,controls.profile.getProperty("keyboardFlight","easy").equals("easy")?tr("Клавиатура: легко","Keyboard: easy"):tr("Клавиатура: профи","Keyboard: advanced"),true);y+=height<270?19:23;String[] presets={tr("Плавный FPV","Gentle FPV"),tr("Сбалансированный","Balanced"),"Acro"};int w=(width-24)/3;for(int i=0;i<3;i++)button(420+i,left+8+i*(w+4),y,w,presets[i],true);}else if(controlsPage==1){int step=Math.min(23,Math.max(19,(height-145)/4));for(int i=0;i<4;i++){button(430+i,left+8,y+i*step,(width-32)/2,VMController.ACTIONS[i]+": "+controls.axisLabel(i),controls.device!=null);button(440+i,left+width-91,y+i*step,83,tr("Инверсия ","Invert ")+(controls.flag(VMController.ACTIONS[i]+".invert","false")?"✓":"—"),controls.device!=null);}button(450,left+8,top+height-53,(width-24)/2,controls.stage==1?tr("2. Завершить диапазон","2. Finish range"):tr("1. Стики в центр: запомнить","1. Center sticks: capture"),controls.device!=null);}else if(controlsPage==2){int n=Math.min(5,rows()-1);for(int i=0;i<n&&feelPage*n+i<FEEL.length;i++){int index=feelPage*n+i;button(500+index*2,left+width-64,y+i*23,24,"−",true);button(501+index*2,left+width-36,y+i*23,24,"+",true);}button(460,left+8,top+height-78,35,"<",feelPage>0);button(461,left+47,top+height-78,35,">",(feelPage+1)*n<FEEL.length);}else{int n=Math.min(5,rows()-1);for(int i=0;i<n&&buttonPage*n+i<VMController.BUTTONS.length;i++){int index=buttonPage*n+i;String key=VMController.BUTTONS[index];button(470+index,left+8,y+i*23,width-16,key+": "+controls.profile.getProperty("button."+key,"—"),controls.device!=null);}button(462,left+8,top+height-78,35,"<",buttonPage>0);button(463,left+47,top+height-78,35,">",(buttonPage+1)*n<VMController.BUTTONS.length);}button(490,controlsPage==1?left+12+(width-24)/2:left+8,top+height-53,controlsPage==1?(width-24)/2:width-16,tr("Сохранить управление","Save controls"),true);}
    public void func_73863_a(int mouseX,int mouseY,float partial){Native.rect(0,0,field_146294_l,field_146295_m,0x99070b10);Native.rect(left,top,left+width,top+height,0xf0111922);Native.rect(left,top,left+width,top+2,0xff49c1a3);line("RV  /  PLAYER MENU",left+10,top+11,0xffe2eee9,width-111);ClientState s=ClientProxy.state;int y=body();if(tab==0){String[] phases={tr("Лобби","Lobby"),tr("Старт через ","Starting in ")+(s==null?0:s.countdownSeconds)+"s",tr("Бой","Round"),tr("Результаты","Results")};line(s==null?tr("Подключение к серверу…","Connecting to server…"):phases[s.phase]+"  ·  "+tr("Игроков ","Players ")+s.players+"  ·  "+tr("Готовы ","Ready ")+s.readyPlayers+"  ·  "+tr("Голоса ","Votes ")+s.votes+"/"+s.votesNeeded,left+10,y+7,0xff9ec6bc,width-20);int info=y+118;if(info<top+height-72)line(s!=null&&s.gearConfirmed?tr("Снаряжение подтверждено. Готовность — ваш выбор.","Gear confirmed. Ready when you choose."):tr("Выберите снаряжение или оставьте своё во вкладке Gear.","Choose gear or keep your inventory in the Gear tab."),left+10,info,0xffc3cdd4,width-20);}else if(tab==1&&s!=null){line(tr("Бюджет ","Budget ")+s.cost+"/"+s.budget+"  ·  "+tr("Нужно мест ","Slots needed ")+s.requiredSlots+"/"+s.freeSlots+(s.cooldownSeconds>0?"  ·  "+s.cooldownSeconds+"s":""),left+10,top+height-29,0xff9ec6bc,width-20);}else if(tab==2&&controls!=null){if(controlsPage==1){int barX=left+width/2+4,barW=Math.max(16,width/2-103);for(int i=0;i<4;i++){int by=y+31+i*Math.min(23,Math.max(19,(height-145)/4));Native.rect(barX,by,barX+barW,by+9,0xff26363e);int fill=(int)((Math.max(-1,Math.min(1,controls.raw[i]))+1)*.5*barW);Native.rect(barX,by,barX+fill,by+9,0xff49c1a3);}}else if(controlsPage==2){int n=Math.min(5,rows()-1);String[] labels={tr("Мёртвая зона","Deadzone"),tr("Экспонента","Expo"),tr("Поворот °/с","Turn °/s"),tr("Сглаживание","Smoothing"),tr("Сглаживание газа","Throttle smoothing"),tr("Экспонента газа","Throttle expo"),tr("Наклон °","Angle limit °"),tr("Крен камеры","Camera roll"),tr("Скорость газа","Throttle rate")};for(int i=0;i<n&&feelPage*n+i<FEEL.length;i++){int index=feelPage*n+i;line(labels[index]+": "+String.format(java.util.Locale.ROOT,"%.3f",controls.setting(FEEL[index],DEFAULT[index])),left+10,y+32+i*23,0xffc3cdd4,width-83);}}line(controlNotice(),left+10,top+height-29,0xff9ec6bc,width-20);}for(int i=0;i<buttons.size();i++){Button b=buttons.get(i);Native.call(b.nativeButton,"func_191745_a",Native.minecraft(),mouseX,mouseY,partial);if(i==focus){Native.rect(b.x,b.y+b.h-1,b.x+b.w,b.y+b.h,0xff49c1a3);}}if(tab!=2){String text=ClientProxy.pending?tr("Обновление…","Updating…"):message();line(text,left+10,top+height-14,0xff9ec6bc,width-20);}else line(tr("Esc: отмена несохранённых изменений · газ сброшен","Esc: discard unsaved changes · throttle cut"),left+10,top+height-14,0xff92a2ad,width-20);}
    private String controlNotice(){String n=controls.notice;if(n.equals("usb"))return tr("USB Joystick: RadioMaster, другие пульты, PS / Xbox.","USB Joystick: RadioMaster, other radios, PS / Xbox.");if(n.equals("range"))return tr("Проведите всеми 4 стиками до краёв, затем завершите.","Move all 4 axes to both ends, then finish.");if(n.equals("calibrated"))return tr("Калибровка готова. Проверьте инверсию и сохраните.","Calibrated. Check inversion and save.");if(n.equals("saved"))return tr("Сохранено. Уберите газ перед возвращением к полёту.","Saved. Lower throttle before returning to flight.");if(n.equals("preset"))return tr("Пресет выбран. Калибровка сохранена; нажмите Сохранить.","Preset selected. Calibration retained; press Save.");if(n.equals("assign"))return tr("Назначьте четыре разные оси.","Assign four different axes.");if(n.equals("disconnected"))return tr("Нет сигнала USB. Переподключите и обновите список.","No USB signal. Reconnect and scan.");if(n.equals("save_failed"))return tr("Не удалось сохранить профиль.","Could not save profile.");if(n.equals("range_missing"))return tr("Нужен полный ход четырёх разных осей и их центр.","Four distinct axes need full range and center.");return tr("Стики в центр; газ пульта временно в середину.","Center sticks; temporarily center radio throttle.");}
    private String message(){if(!ClientProxy.error.isEmpty())return ClientProxy.error.equals("server_unavailable")?tr("Сервер не ответил. Управление доступно локально.","Server did not reply. Controls remain local."):tr("Ответ сервера отклонён.","Server response rejected.");ClientState s=ClientProxy.state;if(s==null)return tr("F7 — меню и управление","F7 — menu and controls");String m=s.message;if(m.equals("inventory_full"))return tr("Недостаточно места. Освободите инвентарь.","Not enough space. Free inventory slots.");if(m.equals("stale_revision"))return tr("Состояние обновлено. Повторите выбор.","State refreshed. Repeat your choice.");if(m.equals("gear_unconfirmed"))return tr("Подтвердите снаряжение или оставьте своё.","Confirm gear or keep your inventory.");if(m.equals("equipped"))return tr("Выбранное снаряжение получено.","Selected gear equipped.");if(m.equals("gear_kept"))return tr("Ваш инвентарь сохранён.","Your inventory retained.");if(m.equals("rate_limited"))return tr("Подождите перед следующим действием.","Wait before the next action.");return tr("Все изменения сессии проверяет сервер.","Session changes are verified by the server.");}
    protected void func_73864_a(int x,int y,int mouse)throws IOException{clickAt(x,y,mouse);}
    public void clickAt(int x,int y,int mouse)throws IOException{if(mouse!=0)return;for(int i=0;i<buttons.size();i++){Button b=buttons.get(i);if(b.enabled&&Boolean.TRUE.equals(Native.call(b.nativeButton,"func_146116_c",Native.minecraft(),x,y))){focus=i;Native.call(b.nativeButton,"func_146113_a",Native.call(Native.minecraft(),"func_147118_V"));activate(b.id);return;}}}
    protected void func_73869_a(char character,int key)throws IOException{if(key==Keyboard.KEY_ESCAPE||key==Keyboard.KEY_F7){Native.display(null);return;}if(key==Keyboard.KEY_TAB){int d=Keyboard.isKeyDown(Keyboard.KEY_LSHIFT)||Keyboard.isKeyDown(Keyboard.KEY_RSHIFT)?-1:1;for(int i=0;i<buttons.size();i++){focus=(focus+d+buttons.size())%buttons.size();if(buttons.get(focus).enabled)break;}}else if((key==Keyboard.KEY_RETURN||key==Keyboard.KEY_SPACE)&&focus>=0&&buttons.get(focus).enabled)activate(buttons.get(focus).id);}
    private void send(Action action,int a,int b){ClientProxy.request(action,a,b);rebuild();}
    private void activate(int id){if(id==1){Native.display(null);return;}if(id==2){send(Action.CHOOSE_LANGUAGE,english()?0:1,0);return;}if(id>=10&&id<=12){tab=id-10;rebuild();return;}if(id>=100&&id<=102)send(Action.CHOOSE_MODE,id-100,0);else if(id>=110&&id<=112)send(Action.CHOOSE_TEAM,id-109,0);else if(id==120)send(Action.SET_READY,ClientProxy.state.ready?0:1,0);else if(id==121)send(Action.VOTE_START,0,0);else if(id==122)send(Action.CANCEL_VOTE,0,0);else if(id==130)send(Action.GO_LOBBY,0,0);else if(id==131)send(Action.GO_TRAINING,0,0);else if(id==132)send(Action.OPEN_GUIDE,0,0);else if(id>=200&&id<=206){gearSlot=id-200;gearPage=0;rebuild();}else if(id==220)send(Action.CHOOSE_GEAR,gearSlot,0);else if(id==221||id==222){gearPage+=id==221?-1:1;rebuild();}else if(id==230)send(Action.CONFIRM_GEAR,0,0);else if(id==231)send(Action.KEEP_GEAR,0,0);else if(id>=300&&id<300+ClientProxy.state.presets.size())send(Action.SELECT_PRESET,ClientProxy.state.presets.get(id-300).id,0);else if(id>=1001)send(Action.CHOOSE_GEAR,gearSlot,id-1000);else if(id>=400)controlAction(id);}
    private void controlAction(int id){if(id>=400&&id<=403)controlsPage=id-400;else if(id==410)controls.scan();else if(id==411)controls.nextDevice();else if(id==412)controls.toggle("enabled","false");else if(id==413)controls.profile.setProperty("kind",controls.profile.getProperty("kind","radio").equals("radio")?"gamepad":"radio");else if(id==414)controls.profile.setProperty("flight",controls.profile.getProperty("flight","angle").equals("angle")?"acro":"angle");else if(id==415)controls.profile.setProperty("keyboardFlight",controls.profile.getProperty("keyboardFlight","easy").equals("easy")?"advanced":"easy");else if(id>=420&&id<=422)controls.preset(id-420);else if(id>=430&&id<=433)controls.axis(id-430);else if(id>=440&&id<=443)controls.toggle(VMController.ACTIONS[id-440]+".invert","false");else if(id==450)controls.calibrate();else if(id==460||id==461)feelPage+=id==460?-1:1;else if(id==462||id==463)buttonPage+=id==462?-1:1;else if(id>=470&&id<=478)controls.button(id-470);else if(id==490)controls.save();else if(id>=500&&id<=517){int i=(id-500)/2;double d=controls.setting(FEEL[i],DEFAULT[i])+(id%2==0?-STEP[i]:STEP[i]);controls.profile.setProperty(FEEL[i],""+Math.max(MIN[i],Math.min(MAX[i],d)));}rebuild();}
}
