import argparse
from copy import deepcopy
import hashlib
import json
from pathlib import Path
import zipfile


BASELINE_SHA256 = '5fddd87a99455edbd85005dd24851591862ab7d065e405597d2def4bc66d1937'
PROTOTYPE_SHA256 = '13d6d8c6daa40aec05ff1e093308628e698f220452bbf30d6bf59d786d26137f'
ALIASES = {
    'prototype.l115a3.sup': 'prototype.l115a3.shoot.sup',
    'prototype.mosin_nagant.sup': 'prototype.mosin_nagant.shoot.sup',
    'prototype.sks.sup': 'prototype.sks.shoot.sup',
    'prototype.p88.distant': 'prototype.p88.shoot.distant',
    'prototype.m14s.distant': 'prototype.m14.distant',
}


def load_pinned(path, digest):
    data = path.read_bytes()
    if hashlib.sha256(data).hexdigest() != digest:
        raise ValueError(f'Unexpected source checksum: {path}')
    with zipfile.ZipFile(path) as archive:
        if archive.testzip():
            raise ValueError(f'Invalid source archive: {path}')
        return {name: archive.read(name) for name in archive.namelist()}


def file_reference(entry):
    name = entry if isinstance(entry, str) else entry['name']
    namespace, resource = name.split(':', 1)
    return f'assets/{namespace}/sounds/{resource}.ogg'


def build(source, prototype, output):
    if output.resolve() in (source.resolve(), prototype.resolve()):
        raise ValueError('Output must differ from both source archives')
    content = load_pinned(source, BASELINE_SHA256)
    native = load_pinned(prototype, PROTOTYPE_SHA256)
    native_events = json.loads(native['assets/modularwarfare/sounds.json'])
    events = {}
    for alias, target in ALIASES.items():
        samples = native_events[target]['sounds']
        if not samples or any(file_reference(entry) not in native for entry in samples):
            raise ValueError(f'Unresolved original event: {target}')
        events[alias] = {'replace': True, 'sounds': [{'name': f'modularwarfare:{target}', 'type': 'event'}]}
    m14 = deepcopy(native_events['prototype.m14.shoot'])
    m14['sounds'] = [entry for entry in m14['sounds'] if file_reference(entry) in native]
    if m14['sounds'] != [f'modularwarfare:m14/shoot{number}' for number in (2, 3, 4)]:
        raise ValueError('Unexpected original M14 samples')
    m14['replace'] = True
    events['prototype.m14.shoot'] = m14
    variations = {
        'prototype.hk416.shoot': ('ar1', 1.0, 32),
        'prototype.hk416.shoot.distant': ('ar1', 0.28, 96),
        'prototype.hk416.shoot.sup': ('silencedm4', 0.7, 32),
    }
    for event, (family, volume, distance) in variations.items():
        samples = []
        for variant in ('a', 'b'):
            resource = f'techguns:guns/{family}_shot_{variant}'
            sample = {'name': resource, 'volume': volume, 'attenuation_distance': distance}
            if file_reference(sample) not in content:
                raise ValueError(f'Missing RV rifle sample: {resource}')
            samples.append(sample)
        events[event] = {'replace': True, 'sounds': samples}
    member = 'assets/modularwarfare/sounds.json'
    if member in content:
        raise ValueError('Baseline unexpectedly contains ModularWarfare overrides')
    content[member] = json.dumps(events, separators=(',', ':')).encode('utf-8')
    content['pack.mcmeta'] = json.dumps({'pack': {'pack_format': 3, 'description': 'RV Combat Audio 1.6 | FPV, weapons and directional rifle audio'}}, separators=(',', ':')).encode('utf-8')
    content['CREDITS.txt'] += (
        '\nRV 1.2: ModularWarfare event aliases reference original, locally installed samples.\n'
        'The M14 event uses its three existing samples; no vendor audio is distributed here.\n'
        'M4A4/HK416 fire uses the existing RV assault-rifle and silenced-rifle remixes\n'
        'for positional mono playback. These are a game sound design, not field recordings.\n'
        'ModularWarfare authors: https://www.curseforge.com/minecraft/mc-mods/modularwarfare\n'
        'Generated by tools/build_vendor_audio.py from pinned RV Combat Audio 1.5.\n'
    ).encode('utf-8')
    output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output, 'w', zipfile.ZIP_DEFLATED, compresslevel=6) as archive:
        for name, data in sorted(content.items()):
            info = zipfile.ZipInfo(name, (2026, 10, 3, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            archive.writestr(info, data)
    report = {
        'status': 'STAGED_NATIVE_PLAYBACK_PENDING',
        'sha256': hashlib.sha256(output.read_bytes()).hexdigest(),
        'sourceSha256': BASELINE_SHA256,
        'prototypeSha256': PROTOTYPE_SHA256,
        'sameWeaponAliases': ALIASES,
        'm14Samples': m14['sounds'],
        'directionalRifleEvents': list(variations),
        'newVendorAudioFiles': 0,
        'existingAudioBytesPreserved': True,
        'nativePlaybackVerified': False,
    }
    output.with_suffix('.json').write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8')
    return report


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Build RV audio compatibility overrides from pinned sources.')
    parser.add_argument('--source', type=Path, required=True)
    parser.add_argument('--prototype', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(build(args.source, args.prototype, args.output)))
