import argparse
import hashlib
import io
import json
from pathlib import Path
import sys
import zipfile

parser=argparse.ArgumentParser()
parser.add_argument('--source',type=Path,required=True)
parser.add_argument('--output',type=Path,required=True)
parser.add_argument('--libraries',type=Path)
parser.add_argument('--apache-burst',action='store_true')
args=parser.parse_args()
if args.libraries:sys.path.insert(0,str(args.libraries))
import numpy as np
import soundfile as sf

if args.apache_burst:
    with zipfile.ZipFile(args.source) as archive:content={name:archive.read(name) for name in archive.namelist()}
    rate=44100
    pcm=np.zeros(97965,dtype=np.float64)
    for shot in range(8):
        name='assets/techguns/sounds/guns/minigun_shot_'+chr(97+shot%4)+'.ogg'
        sample,sample_rate=sf.read(io.BytesIO(content[name]))
        assert sample_rate==rate and sample.ndim==1 and np.all(np.isfinite(sample))
        start=int(shot*.12*rate);end=min(len(pcm),start+len(sample));pcm[start:end]+=sample[:end-start]
    edge=441
    window=np.sin(np.linspace(0,np.pi/2,edge))**2
    pcm[:edge]*=window;pcm[-edge:]*=window[::-1]
    pcm*=.8/np.max(np.abs(pcm))
    stream=io.BytesIO();sf.write(stream,pcm,rate,format='OGG',subtype='VORBIS')
    decoded,actual_rate=sf.read(io.BytesIO(stream.getvalue()))
    assert actual_rate==rate and decoded.ndim==1 and len(decoded)==97965 and np.all(np.isfinite(decoded)) and np.max(np.abs(decoded))<=.88
    member='assets/techguns/sounds/npcs/rv_apache_burst.ogg';content[member]=stream.getvalue()
    events=json.loads(content['assets/techguns/sounds.json'])
    events['npcs.apacheburst']={'category':'hostile','replace':True,'sounds':[{'name':'techguns:npcs/rv_apache_burst','volume':1,'pitch':1,'attenuation_distance':16}]}
    content['assets/techguns/sounds.json']=json.dumps(events,separators=(',',':')).encode()
    content['pack.mcmeta']=json.dumps({'pack':{'pack_format':3,'description':'RV Combat Audio 1.5 | FPV motor, weapons and impacts'}}).encode()
    content['CREDITS.txt']+=b'\nRV 1.1: original RV minigun samples arranged as the NPC helicopter burst.\n'
    args.output.parent.mkdir(parents=True,exist_ok=True)
    with zipfile.ZipFile(args.output,'w',zipfile.ZIP_DEFLATED,compresslevel=6) as archive:
        for name,data in sorted(content.items()):
            item=zipfile.ZipInfo(name,(2026,10,2,0,0,0));item.compress_type=zipfile.ZIP_DEFLATED;archive.writestr(item,data)
    report={'sha256':hashlib.sha256(args.output.read_bytes()).hexdigest(),'source_sha256':hashlib.sha256(args.source.read_bytes()).hexdigest(),'event':'techguns:npcs.apacheburst','member':member,'sample_rate':actual_rate,'channels':1,'seconds':len(decoded)/rate,'decoded_peak':float(np.max(np.abs(decoded))),'originalSampleSource':'RV minigun','shots':8,'nativeEventGain':8,'eventGain':1,'attenuationDistance':16}
    args.output.with_suffix('.json').write_text(json.dumps(report,indent=2),encoding='utf-8');print(json.dumps(report));sys.exit(0)

rate=44100
t=np.arange(rate*4,dtype=np.float64)/rate
pcm=np.zeros_like(t)
for frequency,amplitude in [(83.5,.25),(167,.15),(250.5,.08),(334,.10),(510,.055),(680,.04),(850,.025)]:
    pcm+=amplitude*np.sin(2*np.pi*frequency*t)*(1+.06*np.sin(2*np.pi*13*t))
rng=np.random.default_rng(110)
for frequency,phase in zip(rng.integers(1600,9000,32)/4,rng.uniform(0,2*np.pi,32)):
    pcm+=.002*np.sin(2*np.pi*frequency*t+phase)
pcm-=np.mean(pcm)
edge=441
window=np.sin(np.linspace(0,np.pi/2,edge))**2
pcm[:edge]*=window
pcm[-edge:]*=window[::-1]
pcm*=.48/np.max(np.abs(pcm))
stream=io.BytesIO()
sf.write(stream,pcm,rate,format='OGG',subtype='VORBIS')
decoded,actual_rate=sf.read(io.BytesIO(stream.getvalue()))
assert actual_rate==rate and decoded.ndim==1 and len(decoded)==len(pcm)
assert np.max(np.abs(decoded))<.6
assert abs(decoded[-1]-decoded[0])<.01
with zipfile.ZipFile(args.source) as archive:content={name:archive.read(name) for name in archive.namelist()}
content['assets/mcheli/sounds/rv_fpv_motor.ogg']=stream.getvalue()
sounds=json.loads(content['assets/mcheli/sounds.json'])
sounds['radicon_heli']={'replace':True,'sounds':[{'name':'mcheli:rv_fpv_motor','volume':.72,'pitch':1,'attenuation_distance':32}]}
content['assets/mcheli/sounds.json']=json.dumps(sounds,separators=(',',':')).encode()
content['pack.mcmeta']=json.dumps({'pack':{'pack_format':3,'description':'RV Combat Audio 1.4 | FPV motor, weapons and impacts'}}).encode()
content['CREDITS.txt']+=b'\nRV 1.1: original procedural FPV motor loop; generated by tools/build_fpv_audio.py.\n'
args.output.parent.mkdir(parents=True,exist_ok=True)
with zipfile.ZipFile(args.output,'w',zipfile.ZIP_DEFLATED,compresslevel=6) as archive:
    for name,data in sorted(content.items()):
        item=zipfile.ZipInfo(name,(2026,10,2,0,0,0));item.compress_type=zipfile.ZIP_DEFLATED;archive.writestr(item,data)
report={'sha256':hashlib.sha256(args.output.read_bytes()).hexdigest(),'source_sha256':hashlib.sha256(args.source.read_bytes()).hexdigest(),'sample_rate':actual_rate,'channels':1,'seconds':len(decoded)/rate,'decoded_peak':float(np.max(np.abs(decoded))),'loop_jump':float(abs(decoded[-1]-decoded[0])),'maximum_sample_step':float(np.max(np.abs(np.diff(decoded))))}
args.output.with_suffix('.json').write_text(json.dumps(report,indent=2),encoding='utf-8')
print(json.dumps(report))
